spring:
  application:
    name: EA_ARS
 
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  mail:
    host: smtp.gmail.com
    port: 587
    username: cs544eateam6@gmail.com
    password: cs544ea_Team6
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

server:
  port: 8009
